### ISSUE TITLE
Logging in with QR Code

### ISSUE THREAD

**Issue by no1wafer** [MrApplejuice/BabyBuddyAndroid#21]
Hi,
May I ask for a request to login to Home Assistant ingress servers using QR Code?
It currently doesn't seems to have another way to login to those servers.
Thank you!

**Comment by MrApplejuice** [comment]
Hey there! I need your help here because I am not so familiar with "Home Assistant ingress servers"...

I assume that you are talking about [the home assistant integration, right?](https://github.com/OttPeterR/addon-babybuddy) An regarding QR-code, you refer to the "Add a device" feature of baby-buddy, right?

<img src="https://user-images.githubusercontent.com/542105/231575814-307a660f-504e-4d08-ae82-58f1b84355c5.png" width="50%">

(Don't worry, this is only the login for my local dev-server!)

If you are talking about the qr-code login, this is a feature I totally intend to implement. I even added the source-code for generating the login-QR code myself to the babybuddy webapp. Fiddling around with the three login fields feels kind of horrible, so yes: Totally planned. But I need some time to learn the tech to make it work. Specifically:

- Camera controls on android
- QR code library, probably based around [zxing](https://github.com/zxing/zxing)

**Comment by no1wafer** [comment]
I would like to nudge you to take a look at the solution Grocy implemented in QR Code login.
And that they are open sourced as well!

**Comment by MrApplejuice** [comment]
I am working on this right now. A prototype is already in working order.

Open issues are:
- [ ] Proper handling when device does not have a working camera module
- [ ] Proper handling when someone denied access to the camera
  - When someone denies access to the camera and does so again, the permission-check auto-denies access, but the app does not know this and just shows a sort-of buggy response
- [ ] Minimizing the app while on the QR-code login screen crashes the app
  - The reason for this is that the QR-code login should be stopped correctly when minimizing the app. Right now it is just not bound to the right lifecycle listeners.
- [ ] Preview screen is not always 4:3 as I meant it to be.
- [ ] Building the zxing-library is a total mess right now, and is not integrated into the build pipeline at all
- [ ] Actually logging in does not work
  - [ ] Special attention: The nav-stack needs to be unwound before performing the actual login.

**Comment by MrApplejuice** [comment]
- [ ] Missing menu

**Comment by MrApplejuice** [comment]
- [ ] Check dark mode
- [ ] Update about page: Add lib-zxing!

**Comment by MrApplejuice** [comment]
- [ ] Warning about logging into unsafe `http`-server is missing for QR-Code logins

**Comment by MrApplejuice** [comment]
I just discovered that the qr-codes that the babybuddy webapp generates are bugged. When placed behind a reverse-proxy, like, for example, homeassistant uses, the qr-code encoded in the qr-code is wrong. This needs to be fixed before this goes live, because otherwise QR-code logins will barely work anywhere.

**Comment by MrApplejuice** [comment]
I was able to reverse-engineer what needs to be done to also support homeassistant ingress servers: Alongside the authentication token for babybuddy, the `ingress_session` needs to be stored and set as a cookie when using the homeassistant ingress server.

I am not sure how long the `ingress_session` is valid, however. These things need to be researched. I will write a working prototype for homeassistant first and release it as "beta".

**Comment by MrApplejuice** [comment]
Issue https://github.com/OttPeterR/addon-babybuddy/issues/47 has three outstanding PRs. That should fix this.

Homeassistant-support will be release as "beta" for now. I am really not sure if this is implemented in a stable way...

**Comment by MrApplejuice** [comment]
For reference: There really should be a "manual" way to login to homeassistant complemeting the QR-code way, to allow a save, manual workaround for issues while logging in... When that one exists, the "beta" state can be removed.

**Comment by MrApplejuice** [comment]
One last action point for this:
- [ ] Add documentation and "beta warning" for detected home assistant logins

**Comment by MrApplejuice** [comment]
Meh... testing reveals remaining bugs. Several:

- [ ] If the server sends the wrong URL, sometimes the error message is empty and not handled correctly causing an error of "read failed on null object". Need to trace this issue in the BabyBuddyClient...
- [ ] When logging in successfully with the QR code using https, the app just crashes...

**Comment by MrApplejuice** [comment]
- [ ] Add docs

**Comment by MrApplejuice** [comment]
What a long trajectory. But this feature seems to be fully implemented for now! :tada:
